name: the_tarot_guru
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  mysql1: ^0.20.0
  http: ^1.2.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  get: ^4.6.6
  get_storage: ^2.0.3
  audioplayers: ^6.0.0
  flip_card: ^0.7.0
  intl: ^0.18.1
  animations: ^2.0.3
  flutter_svg: ^2.0.10+1
  connectivity: ^3.0.6
  google_fonts: ^6.2.1
  razorpay_flutter: ^1.3.6
  dynamic_multi_step_form: ^1.1.1
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Screen_Backgrounds/
    - assets/images/cards/
    - assets/images/other/
    - assets/images/intro/
    - assets/images/patterns/osho/
    - assets/images/patterns/rider/
    - assets/images/tarot_cards/Osho Zen/
    - assets/images/tarot_cards/Osho Zen/Clouds/
    - assets/images/tarot_cards/Osho Zen/Earth/
    - assets/images/tarot_cards/Osho Zen/Fire/
    - assets/images/tarot_cards/Osho Zen/Major Arcana/
    - assets/images/tarot_cards/Osho Zen/Water/
    - assets/images/tarot_cards/Rider Waite/
    - assets/images/tarot_cards/Rider Waite/Cups/
    - assets/images/tarot_cards/Rider Waite/Pentacles/
    - assets/images/tarot_cards/Rider Waite/Swords/
    - assets/images/tarot_cards/Rider Waite/Major Arcana/
    - assets/images/tarot_cards/Rider Waite/Wands/
    - assets/json/